version: "3"

services:
  learn-mysql:
    image: mariadb/server:10.3
    environment:
      MARIADB_ROOT_PASSWORD: 'learn'
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - learn-mysql:/var/lib/mysql
    networks:
      - learn-mysql

  learn-mysql-flyway:
    build:
      context: flyway
    image: learn-mysql-flyway:latest
    command: migrate
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - learn-mysql
    networks:
      - learn-mysql

volumes:
  learn-mysql:

networks:
  learn-mysql:
